name = "todoify"
version = "1.0.0"

description = "â˜‘ï¸ create placeholders for missing implementations"
licences = ["Apache-2.0"]

repository = { type = "github", user = "daniellionel01", repo = "parrot" }


[documentation]
pages = [
  { title = "Changelog", path = "changelog.html", source = "./CHANGELOG.md" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
